include common.mk

LIBPOIS0N_NAME = libpois0n
LIBPOIS0N_TARGETS = $(LIBPOIS0N_NAME)$(OS_STATIC_EXT) $(LIBPOIS0N_NAME)$(OS_SHARED_EXT)
LIBPOIS0N_DIRECTORY = syringe

UTILITIES__TARGETS = injectpois0n$(OS_EXEC_EXT) tetheredboot$(OS_EXEC_EXT)

TARGETS = $(LIBPOIS0N_TARGETS) $(UTILITIES_TARGETS)

$(LIBPOIS0N_TARGETS):
	$(MAKE) $(@) -C $(LIBPOIS0N_DIRECTORY)
	$(CP) $(LIBPOIS0N_DIRECTORY)/$(@) $(@)

$(UTILITIES_TARGETS): $(LIBPOIS0N_TARGETS)

all: $(TARGETS)

clean:
	$(RM) $(TARGETS)